### PR TITLE
[1.19] Reusable bucket textures

### PR DESCRIPTION
**Pull request by cech12**
I am the developer of the mod [Ceramic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket). I decided to develop a library mod ([BucketLib](https://www.curseforge.com/minecraft/mc-mods/bucketlib)) to make it easier for mod developers to add own buckets.

To make your mod compatible with my library mod but also to be more compatible with other mods, I split your bucket content textures from the underlying bucket, reordered and renameed some texture & model files to make them reusable. (I did not change them ;D)

You can test the compatibility when you install [Ceramic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket/files) and [BucketLib](https://www.curseforge.com/minecraft/mc-mods/bucketlib/files)

See also the [Developer Guide](https://github.com/cech12/BucketLib/wiki/Developer-Guide) to be compatible in the future. :)

### CODE REVIEW

**Comment by SmellyModder** [comment]
What exactly is the compatibility benefit of splitting apart our bucket content from the bottom bucket?

I understand this makes it easier for other resource packs to use our bucket contents in their item models, but that doesn't make it more compatible.
I don't see why our models must be changed when this is all just texture files.
Unless I'm misunderstanding, this PR would fit better as a public-use resource pack or perhaps just a folder of all the bucket contents.

**Comment by cech12** [comment]
The benefit is that your mod would not need an extra resource pack to enable other mods and resource packs to use your bucket content textures.

If you change or add these textures it has an direct impact to all mods and resource packs that are using these textures.

The name changes are made to fit the entity name to make it more reusable by getting the textures by using the entity names. The model changes where made to fit the new texture locations. 

My mod for example searches for all Bucketable (interface) entities and searches the content textures in the "bucket_content" by the entity name and the corresponding mod name. 

Aquaculture (PR 336) and Alex's Mobs (PR 995) are also using this type of order and the splitted textures to let other reuse their changeable textures.

**Comment by SmellyModder** [comment]
Considering the enforcing behavior you describe here, your API sounds fitter as a Forge PR. This PR also puts a maintenance burden on us. Our team will think about this.

**Comment by cech12** [comment]
The interface (Bucketable) described in my comment is part of vanilla Minecraft and is already used by your mod and Blueprint in the same way. Therefore, this PR does not contain any changes in this regard either.

For maintenance, the only important thing is that the texture of the bucket contents remain separate from the bucket. Therefore, I estimate the maintenance effort as very low. But whether you want to support it is of course your decision. :)

I would be happy if you decide to do so. :)

**Comment by bageldotjpg** [comment]
Quite the delay on this, apologies, but we're gonna stick to the vanilla method as this is quite the burden and not an established format so there's a lot of inconsistency and could even cause issues with resource packs

**Pull request closed without merging**
